[versions]
# https://plugins.jetbrains.com/docs/intellij/using-kotlin.html#kotlin-standard-library
kotlin = "2.2.20"
# https://github.com/JetBrains/rd/releases
rdGen = "2025.3.1"

[libraries]
kotlinStdLib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
openTest4J = "org.opentest4j:opentest4j:1.3.0"
rdGen = { group = "com.jetbrains.rd", name = "rd-gen", version.ref = "rdGen" }

[plugins]
changelog = "org.jetbrains.changelog:2.2.1"
gradleIntelliJPlatform = "org.jetbrains.intellij.platform:2.10.4"
gradleJvmWrapper = "me.filippov.gradle.jvm.wrapper:0.14.0"
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
